### ISSUE TITLE
1° Feedback Portafolio

### ISSUE THREAD

**Issue by nerdale** [nahytar/portafolio#1]
Mayra,

1. Tu portafolio se ve muy profesional, utilizas una paleta de colores bastante clásica y limpia.

2. Ojo con un scroll horizontal que tienes, quizas hay un padding, margin o elemento que está fuera de su contenedor.

3. Si bien el diseño es bastante clásico, eso no significa que la diagramación sea poco dinámica, con eso me refiero por ejemplo a como distribuyes los elementos en la sección Proyectos. Te dejo un [ejemplo distinto](http://preview.themeforest.net/item/accio-responsive-parallax-one-page-site-template/full_screen_preview/6279726) (debes ir a la sección **folio**)

4. Falta un poquito de información sobre ti :smile_cat: 

5. Te recomiendo jugar con las transiciones entre las secciones y con la aparición de los elementos en cada sección, de esa manera podrás darle un dinamismo a tu portafolio, generandole así más personalidad.

6. Recuerda que debe ser full responsive.

7. Cualquier cosa andamos por acá.

Saludos.

**Comment by nahytar** [comment]
Gracias.
